import maplibregl from 'maplibre-gl';
import { Capacitor } from '@capacitor/core';
import { Geolocation } from '@capacitor/geolocation';
import { Network } from '@capacitor/network';
import { Protocol } from 'pmtiles';
import 'maplibre-gl/dist/maplibre-gl.css';
import './style.css';
import { POIS, BASES, CAT_LABEL, baseForDay, haversineKm, type Poi } from './data';
import { loadPlan, addToDay, removeFromDay, toggleStop, recommend, buildDay, applyDay, dayPois, routeOrder, googleUrl, loadLocks } from './planner';

type OfflineManifest={version:number;id:string;filename:string;format:string;minzoom:number;maxzoom:number;region:string;status:string;sourceLayers:string[];attribution:string};
const status=document.querySelector('#status')!; const network=document.querySelector('#network')!; const offline=document.querySelector('#offline')!; const offlineDetail=document.querySelector('#offline-detail')!;
const protocol=new Protocol(); maplibregl.addProtocol('pmtiles',protocol.tile); const assetUrl=(p:string)=>new URL(p,document.baseURI).toString();
let map:maplibregl.Map; let marker:maplibregl.Marker|null=null; let nativeWatchId:string|null=null; let activeDay=1;

async function manifest():Promise<OfflineManifest|null>{try{const r=await fetch(assetUrl('offline/map.json'),{cache:'no-store'});if(!r.ok)throw 0;return await r.json() as OfflineManifest}catch{return null}}
async function installed(m:OfflineManifest|null){if(!m||m.format!=='pmtiles')return false;try{return (await fetch(assetUrl(`offline/${m.filename}`),{method:'HEAD',cache:'no-store'})).ok}catch{return false}}
function baseStyle():maplibregl.StyleSpecification{return{version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#eef3f5'}}]}}
function offlineStyle(m:OfflineManifest):maplibregl.StyleSpecification{const source=`pmtiles://${assetUrl(`offline/${m.filename}`)}`;const has=(x:string)=>m.sourceLayers.includes(x);const layers:maplibregl.LayerSpecification[]=[{id:'background',type:'background',paint:{'background-color':'#eef3f5'}}];if(has('water'))layers.push({id:'water',type:'fill',source:'kreta','source-layer':'water',paint:{'fill-color':'#a9d7e8'}});if(has('landuse'))layers.push({id:'landuse',type:'fill',source:'kreta','source-layer':'landuse',paint:{'fill-color':'#e7eadf','fill-opacity':.7}});if(has('transportation')){layers.push({id:'roads-casing',type:'line',source:'kreta','source-layer':'transportation',minzoom:9,paint:{'line-color':'#b6bdc4','line-width':['interpolate',['linear'],['zoom'],9,1.5,14,6]}});layers.push({id:'roads',type:'line',source:'kreta','source-layer':'transportation',minzoom:7,paint:{'line-color':'#fff','line-width':['interpolate',['linear'],['zoom'],7,.6,14,4]}})}return{version:8,sources:{kreta:{type:'vector',url:source,attribution:m.attribution}},layers}}
function showPosition(pos:{coords:{latitude:number;longitude:number;accuracy:number;heading?:number|null}}){const c=pos.coords,ll:[number,number]=[c.longitude,c.latitude];if(!marker)marker=new maplibregl.Marker({color:'#1565c0'}).setLngLat(ll).addTo(map);else marker.setLngLat(ll);status.textContent=`GPS: ${c.latitude.toFixed(5)}, ${c.longitude.toFixed(5)} · ±${Math.round(c.accuracy)} m${c.heading!=null?` · ${Math.round(c.heading)}°`:''}`}
async function startGps(){try{if(Capacitor.isNativePlatform()){const p=await Geolocation.requestPermissions();if(p.location!=='granted'&&p.coarseLocation!=='granted')throw 0;nativeWatchId=await Geolocation.watchPosition({enableHighAccuracy:true,timeout:15000,maximumAge:2000},(pos,err)=>{if(err)status.textContent=`GPS hiba: ${err.message}`;else if(pos)showPosition(pos)})}else if('geolocation'in navigator)navigator.geolocation.watchPosition(showPosition,e=>status.textContent=`GPS hiba: ${e.message}`,{enableHighAccuracy:true,maximumAge:2000,timeout:10000});else status.textContent='A készülék nem támogat GPS-helymeghatározást.'}catch{status.textContent='A GPS-engedély nem érhető el.'}}
async function refreshNetwork(){try{const s=await Network.getStatus();network.textContent=s.connected?'ONLINE':'OFFLINE'}catch{network.textContent=navigator.onLine?'ONLINE':'OFFLINE'}}

function openExternal(url:string){window.open(url,'_blank','noopener,noreferrer')}
function createPlanner(){
 const panel=document.createElement('section');panel.id='plannerPanel';panel.innerHTML=`<div class="plannerHead"><b>🧭 14 napos tervező</b><button id="closePlanner">×</button></div><div class="plannerDays" id="plannerDays"></div><div class="plannerPrefs"><select id="weather"><option value="good">☀️ Jó idő</option><option value="rain">🌧️ Eső</option><option value="wind">🌬️ Szél</option></select><select id="drive"><option value="low">🚶 Kevés autó</option><option value="medium">🚗 Közepes</option><option value="high">🚗 Több vezetés</option></select><select id="duration"><option value="short">1–2 óra</option><option value="half">Fél nap</option><option value="full" selected>Egész nap</option></select><select id="mode"><option value="mixed">Vegyes</option><option value="nature">🌿 Természet</option><option value="culture">🏛️ Kultúra</option><option value="beach">🏖️ Strand</option></select></div><div class="plannerActions"><button id="buildDay">✨ Nap összeállítása</button><button id="routeDay">🚗 Útvonal</button></div><div id="plannerContent"></div>`;document.body.appendChild(panel);
 const days=panel.querySelector('#plannerDays')!;for(let d=1;d<=14;d++){const b=document.createElement('button');b.textContent=`D${d}`;b.className=d===activeDay?'active':'';b.onclick=()=>{activeDay=d;refreshPlanner()};days.appendChild(b)}
 panel.querySelector('#closePlanner')!.addEventListener('click',()=>panel.classList.remove('show'));
 panel.querySelector('#buildDay')!.addEventListener('click',()=>{const prefs=getPrefs();applyDay(activeDay,buildDay(activeDay,prefs));refreshPlanner();renderDayOnMap()});
 panel.querySelector('#routeDay')!.addEventListener('click',()=>openExternal(googleUrl(activeDay)));
 return panel;
}
function getPrefs(){return{weather:(document.querySelector('#weather') as HTMLSelectElement).value as 'good'|'rain'|'wind',drive:(document.querySelector('#drive') as HTMLSelectElement).value as 'low'|'medium'|'high',duration:(document.querySelector('#duration') as HTMLSelectElement).value as 'short'|'half'|'full',mode:(document.querySelector('#mode') as HTMLSelectElement).value as 'mixed'|'nature'|'culture'|'beach'}}
function refreshPlanner(){const panel=document.querySelector('#plannerPanel')!;panel.querySelectorAll('.plannerDays button').forEach((b,i)=>b.classList.toggle('active',i+1===activeDay));const base=baseForDay(activeDay),pois=dayPois(activeDay),locks=loadLocks()[`D${activeDay}`]||[],recs=recommend(activeDay,getPrefs());const content=panel.querySelector('#plannerContent')!;content.innerHTML=`<div class="baseInfo">D${activeDay} · indulás: <b>${base.name}</b>${activeDay===14?' · vége: Chania repülőtér':''}</div><h4>Mai terv <small>${pois.length} megálló</small></h4>${pois.length?pois.map((p,i)=>`<div class="planRow"><span>${i+1}. <b>${p.name}</b><small>${CAT_LABEL[p.cat]} · ${p.note}</small></span><button data-remove="${p.id}">−</button><button data-lock="${p.id}">${locks.includes(p.id)?'🔒':'🔓'}</button></div>`).join(''):'<p class="muted">Még nincs megálló. Az „Nap összeállítása” 2–4 egymáshoz illő pontot választ.</p>'}<h4>Ajánlott megállók</h4>${recs.map(p=>`<div class="recRow"><span><b>${p.name}</b><small>${CAT_LABEL[p.cat]} · ${Math.round(haversineKm(base,p))} km légvonalban · ${p.note}</small></span><button data-add="${p.id}">＋</button></div>`).join('')}`;
 content.querySelectorAll('[data-add]').forEach(x=>x.addEventListener('click',()=>{addToDay(activeDay,(x as HTMLElement).dataset.add!);refreshPlanner();renderDayOnMap()}));content.querySelectorAll('[data-remove]').forEach(x=>x.addEventListener('click',()=>{removeFromDay(activeDay,(x as HTMLElement).dataset.remove!);refreshPlanner();renderDayOnMap()}));content.querySelectorAll('[data-lock]').forEach(x=>x.addEventListener('click',()=>{toggleStop(activeDay,(x as HTMLElement).dataset.lock!);refreshPlanner()}));
}
function renderDayOnMap(){if(!map)return;document.querySelectorAll('.poi-marker').forEach(x=>x.remove());dayPois(activeDay).forEach((p,i)=>{const el=document.createElement('div');el.className='poi-marker';el.textContent=String(i+1);new maplibregl.Marker({element:el}).setLngLat([p.lon,p.lat]).addTo(map)})}
function showPlanner(){const p=document.querySelector('#plannerPanel')!;p.classList.add('show');refreshPlanner()}
function wireBottom(){const buttons=[...document.querySelectorAll('.bottom button')];buttons[0]?.addEventListener('click',()=>document.querySelector('#plannerPanel')?.classList.remove('show'));buttons[1]?.addEventListener('click',()=>{activeDay=1;showPlanner()});buttons[2]?.addEventListener('click',showPlanner);buttons[3]?.addEventListener('click',showPlanner)}

async function init(){const m=await manifest(),ok=await installed(m);offline.classList.toggle('installed',ok);offline.classList.toggle('missing',!ok);offline.textContent=ok?'✓ Offline térkép':'○ Offline térkép';offlineDetail.textContent=ok?`Kréta vektoros térkép · zoom ${m?.minzoom}–${m?.maxzoom}`:'A PMTiles adatcsomag még nincs telepítve.';map=new maplibregl.Map({container:'map',center:[24.9,35.2],zoom:8,style:ok&&m?offlineStyle(m):baseStyle(),attributionControl:true});map.addControl(new maplibregl.NavigationControl({showCompass:true}),'top-right');map.on('load',()=>{void startGps();renderDayOnMap()});await refreshNetwork();try{await Network.addListener('networkStatusChange',refreshNetwork)}catch{}createPlanner();wireBottom()}
(document.querySelector('#locate') as HTMLButtonElement).onclick=async()=>{await startGps();if(marker)map.flyTo({center:marker.getLngLat(),zoom:14})};void init();window.addEventListener('beforeunload',()=>{if(nativeWatchId)void Geolocation.clearWatch({id:nativeWatchId})});
